name: Link Checker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build --config _config.yml

    - name: Check links and generate report
      uses: lycheeverse/lychee-action@v2
      with:
        args: |
          --exclude 'localhost'
          './**/*.html'
        output: ./lychee-report.md
        workingDirectory: ./_site
        fail: true

    - name: Upload link check report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: link-check-report
        path: lychee-report.md
